# # Form implementation generated from reading ui file 'TSP.ui'
# #
# # Created by: PyQt6 UI code generator 6.4.2
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic6 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt6 import QtCore, QtGui, QtWidgets


# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(802, 672)
#         self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.label = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(10, 510, 49, 16))
#         self.label.setObjectName("label")
#         self.sbDelayTime = QtWidgets.QDoubleSpinBox(parent=self.centralwidget)
#         self.sbDelayTime.setGeometry(QtCore.QRect(10, 530, 101, 22))
#         self.sbDelayTime.setMinimum(0)
#         self.sbDelayTime.setMaximum(10)
#         self.sbDelayTime.setObjectName("sbDelayTime")
#         self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(10, 570, 131, 16))
#         self.label_2.setObjectName("label_2")
#         self.sbNumberDestinations = QtWidgets.QSpinBox(parent=self.centralwidget)
#         self.sbNumberDestinations.setGeometry(QtCore.QRect(10, 590, 101, 22))
#         self.sbNumberDestinations.setObjectName("sbNumberDestinations")
#         self.btStart = QtWidgets.QPushButton(parent=self.centralwidget)
#         self.btStart.setGeometry(QtCore.QRect(160, 530, 75, 24))
#         self.btStart.setObjectName("btStart")
#         self.btStop = QtWidgets.QPushButton(parent=self.centralwidget)
#         self.btStop.setGeometry(QtCore.QRect(160, 560, 75, 24))
#         self.btStop.setObjectName("btStop")
#         self.tbResult = QtWidgets.QTextBrowser(parent=self.centralwidget)
#         self.tbResult.setGeometry(QtCore.QRect(280, 531, 511, 181))
#         self.tbResult.setObjectName("tbResult")
#         self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(280, 510, 49, 16))
#         self.label_3.setObjectName("label_3")
#         self.canvaWidget = MplWidget(parent=self.centralwidget)
#         self.canvaWidget.setGeometry(QtCore.QRect(10, 10, 781, 491))
#         self.canvaWidget.setObjectName("canvaWidget")
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 22))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)

#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)

#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "TSP with Simulated Annealing"))
#         self.label.setText(_translate("MainWindow", "Delay (s)"))
#         self.label_2.setText(_translate("MainWindow", "Number of Destinations"))
#         self.btStart.setText(_translate("MainWindow", "Start"))
#         self.btStop.setText(_translate("MainWindow", "Stop"))
#         self.label_3.setText(_translate("MainWindow", "Result"))
# from mplwidget import MplWidget

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TSPetVYWI.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt6 import QtCore, QtGui, QtWidgets
import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 672)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(680, 30, 49, 16))
        self.label.setObjectName("label")
        self.sbDelayTime = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.sbDelayTime.setGeometry(QtCore.QRect(680, 50, 101, 22))
        self.sbDelayTime.setMinimum(1)
        self.sbDelayTime.setMaximum(10)
        self.sbDelayTime.setObjectName("sbDelayTime")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 90, 131, 16))
        self.label_2.setObjectName("label_2")
        self.sbNumberDestinations = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.sbNumberDestinations.setGeometry(QtCore.QRect(680, 110, 101, 22))
        self.sbNumberDestinations.setObjectName("sbNumberDestinations")
        self.btStart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btStart.setGeometry(QtCore.QRect(820, 50, 75, 24))
        self.btStart.setObjectName("btStart")
        self.btStop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btStop.setGeometry(QtCore.QRect(820, 110, 75, 24))
        self.btStop.setObjectName("btStop")
        self.tbResult = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.tbResult.setGeometry(QtCore.QRect(620, 440, 291, 181))
        self.tbResult.setObjectName("tbResult")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 410, 49, 16))
        self.label_3.setObjectName("label_3")
        self.canvaWidget = MplWidget(parent=self.centralwidget)
        self.canvaWidget.setEnabled(True)
        self.canvaWidget.setGeometry(QtCore.QRect(10, 10, 601, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvaWidget.sizePolicy().hasHeightForWidth())
        self.canvaWidget.setSizePolicy(sizePolicy)
        self.canvaWidget.setAutoFillBackground(False)
        self.canvaWidget.setStyleSheet("image: url(:/mapBackground/ban-do-dien-tich-cac-quan-tphcm-full-hd.jpg);")
        self.canvaWidget.setObjectName("canvaWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TSP with Simulated Annealing"))
        self.label.setText(_translate("MainWindow", "Delay (s)"))
        self.label_2.setText(_translate("MainWindow", "Number of Destinations"))
        self.btStart.setText(_translate("MainWindow", "Start"))
        self.btStop.setText(_translate("MainWindow", "Stop"))
        self.label_3.setText(_translate("MainWindow", "Result"))
from mplwidget import MplWidget

